# Workflow to test the spelling within the PR

name: Spell Checker

on:
  pull_request:
    # Not specifying a type, lets it run on an PR update

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    steps:
      - uses: actions/checkout@v3

      - uses: tbroadley/spellchecker-cli-action@v1
        with:
          quiet: true # Dont output anything if the file contains no spelling mistakes
          files: "docs/**/**/*.md !docs/.vuepress"
          language: "en-US"
          dictionaries: "./tools/spell-checker-dictionary.txt"
